import os

def generate_automation_script(task_description: str, task_name: str = "auto_script") -> str:
    """
    Generates a Python automation script based on observed repetitive behavior.
    """
    prompt = f"""
    You are an expert Python RPA developer. 
    The background observer noticed the user doing the following repetitive task manually:
    "{task_description}"
    
    Please write a complete, safe, and robust Python script to automate this.
    Use libraries like pandas, openpyxl, os, or shutil where appropriate.
    Do NOT include any markdown formatting, only pure Python code.
    """
    
    # Mocking LLM for now unless key is present
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key or api_key == "your_key_here":
        script_code = f"""import pandas as pd
import os

# Auto-Generated Script for: {task_name}
# Detected Behavior: {task_description}

def run_automation():
    print("Running automated workflow...")
    # This is a mocked automation generated by the Shadow Auto engine.
    # In production, this would contain the pandas/openpyxl logic to execute
    # the exact data transformations observed on screen.
    
if __name__ == "__main__":
    run_automation()
"""
    else:
        try:
            from anthropic import Anthropic
            client = Anthropic(api_key=api_key)
            response = client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1500,
                messages=[{"role": "user", "content": prompt}]
            )
            script_code = response.content[0].text.replace("```python", "").replace("```", "").strip()
        except Exception as e:
            script_code = f"# Error generating script: {str(e)}"
            
    # Save script to a safe directory
    save_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "automations", "pending")
    os.makedirs(save_dir, exist_ok=True)
    
    file_path = os.path.join(save_dir, f"{task_name}.py")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(script_code)
        
    return file_path

if __name__ == "__main__":
    # Test
    path = generate_automation_script("User opened a CSV, found the word 'Pending' and replaced it with 'Resolved', then saved.", "resolve_pending_csv")
    print(f"Shadow Automation script generated at: {path}")
